# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gocurl < Formula
  desc "A golang HTTP curl-like tool"
  homepage "https://github.com/mrsimi/gocurl"
  version "1.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/mrsimi/gocurl/releases/download/v1.3/gocurl_Darwin_arm64.tar.gz"
      sha256 "08c23fe0aa5845273b733b8fd872c8684026d8d6d22f1dba3ee47c82272f05a6"

      def install
        bin.install "gocurl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mrsimi/gocurl/releases/download/v1.3/gocurl_Darwin_x86_64.tar.gz"
      sha256 "6e7d9caa896df0729619dfd2f3b1ef9b755f73f475f94e3f5fc9a2d9da7f1d47"

      def install
        bin.install "gocurl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mrsimi/gocurl/releases/download/v1.3/gocurl_Linux_arm64.tar.gz"
      sha256 "29b640f9f08b5c847d5559a35a164a0a733e7f6ee37f21cdc2b7695971ab2033"

      def install
        bin.install "gocurl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mrsimi/gocurl/releases/download/v1.3/gocurl_Linux_x86_64.tar.gz"
      sha256 "fec4c95c22ab30e6ee4076e81aee150ab590f1387eb6bda640ab301697ae77bd"

      def install
        bin.install "gocurl"
      end
    end
  end
end
