# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gocurl < Formula
  desc "A golang HTTP curl-like tool"
  homepage "https://github.com/mrsimi/gocurl"
  version "1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mrsimi/gocurl/releases/download/v1.0/gocurl_Darwin_x86_64.tar.gz"
      sha256 "e193bea0dc93a1b0b113cc494fb7e8c6ed964316a614538697aec0b5d3a16843"

      def install
        bin.install "gocurl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mrsimi/gocurl/releases/download/v1.0/gocurl_Darwin_arm64.tar.gz"
      sha256 "4b9d2a016ba977956cf8e13e61cd56bb16f05d9a8303c614ac066e5a85d7c997"

      def install
        bin.install "gocurl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mrsimi/gocurl/releases/download/v1.0/gocurl_Linux_arm64.tar.gz"
      sha256 "0bd3d58eb60f76158cae4064eb63455f54b415d4ea93fce445fcb9c734daaca6"

      def install
        bin.install "gocurl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mrsimi/gocurl/releases/download/v1.0/gocurl_Linux_x86_64.tar.gz"
      sha256 "704a17ee9c1cff9a8410998b669f39bb372d22f836748912c22900894ecf01d6"

      def install
        bin.install "gocurl"
      end
    end
  end
end
